### ISSUE TITLE
Incompatible with Emacs 25.3/Win10-64? 

### ISSUE THREAD

**Issue by Arjay-El** [weirdNox/org-noter#10]
I cannot install this package and receive this message. Is there a limitation where it can be installed?

org-noter is an incompatible package.
     Status: Incompatible because it depends on uninstallable packages.
    Archive: melpa
    Version: 20180205.1306
    Summary: A synchronized, Org-mode, document annotator
   Requires: emacs-24.4, cl-lib-0.6, org-9.0 (not available)
   Homepage: https://github.com/weirdNox/org-noter

**Comment by weirdNox** [comment]
I don't use Windows so I can't say for sure, but I think that means you don't have the latest Org-mode installed. What do you get when you run `org-version`? If it is less than 9.0, then that is the problem, because that's the minimum version required.

[Check this post on reddit for more information about that specific problem](https://www.reddit.com/r/emacs/comments/7tvz89/orgnoter_a_synchronized_orgmode_document_annotator/dtgh08k/).

**Comment by Arjay-El** [comment]
I upgraded to org 9.x and it runs as you stated up to the point where I specify a pdf. I receive a message
org-note --create session: This document handler is not supported :/

Do you know what would trigger this message?

**Comment by Nebucatnetzer** [comment]
@Arjay-El Reading PDFs in Emacs works as it should without org-noter?

**Comment by weirdNox** [comment]
@Arjay-El That error message occurs when you use a mode that is not doc-view-mode or pdf-view-mode. Are you trying to open a PDF file or some other type? What document viewer do you use?

**Comment by weirdNox** [comment]
Ok, that's great it works for you now :) 

Closing the issue.
