### ISSUE TITLE
Percise note capture is not precise at all for page position!

### ISSUE THREAD

**Issue by OmarAshkar** [weirdNox/org-noter#110]
Hello,
The package is great when you do import skeleton. I like that it creates headings and annotation is a precise way. (i.e page + relative position).  However, when I press c-i. It returns the pages number with header of page name. What is the aim of that at all!

My intuition is that c-i would return the selected text with :Noter_PAGE: (page+ position). But it returns only an automated header "Notes for page #" and a `loose` position for :Noter_page: page. 

I don't see this to be the most helpful. Mostly the pdf I am having don't include an outline, so instead of copying the header and paste to the org file, I would like to press c-i on selected text, then get this text inserted as a header with precise location.

Hope you understand my needs!

**Comment by OmarAshkar** [comment]
I was using it wrong. Thank you for your excellent work

**Comment by AtomicNess123** [comment]
How did you manage to see a pointer in the specific location? Thanks!

**Comment by OmarAshkar** [comment]
@AtomicNess123 You run M-x `org-noter-insert-precise-note` command on the pdf buffer after highlighting text of interest. It will insert the page number and location of the words you highlighted.

**Comment by AtomicNess123** [comment]
Thanks so much. It works. The only drawback is that when I click on the pointer, the pdf-tools "note-taking" feature opens, instead of jumping to the pertinent heading in the org-noter document. Another difference I spotted when comparing with your screencast video is that the link for precise notes is made using the link pdf: and not pdftools:. When I do C-c C-o (org-open-at-point), it won't recognize it ("no match") and prompt me to "create this as a new heading". Thanks!
