### ISSUE TITLE
spacemacs support

### ISSUE THREAD

**Issue by x61** [weirdNox/org-noter#18]
Does this support `spacemacs`? I have spacemacs and encountered the following error message `helm-M-x: This document handler is not supported :/`. No PDF file was produced. If this is spacemacs related, which I don't think it should be, is it possible to port it to work in spacemacs as well?

**Comment by weirdNox** [comment]
Yes, in theory it should be supported. But that's weird, it looks like you are running org-noter inside the helm-M-x buffer, instead of doing it in the notes file or PDF. Could you try disabling Helm and running the command again?

I use Ivy myself and never encountered this problem, but from the error message I would say Helm is not executing the command in the correct buffer.

**Comment by x61** [comment]
I do not believe this is working well in `spacemacs`. I switched to ivy and ran `M-x org-noter` on an org file  and was presented with two org buffers, one called `Include`, and the other is called `Notes of Include`. No pdf was opened. How do I get it to open pdf file?

**Comment by weirdNox** [comment]
Ok, thanks for the report, I'll install spacemacs and try to reproduce the problem. Do you have any additional configuration?

**Comment by x61** [comment]
Thanks for the fine tool. I have other settings but don't think it affects `org-noter`. How do I have it to open `pdf-tools` or any pdf file?  Do I need to do any setting? I have `pdf-tools` installed and have used it in `spacemacs`.

**Comment by weirdNox** [comment]
Hello there, I downloaded Spacemacs and installed Helm with the minimal base packages. After, I installed `org-noter` with `package-install` (which also installed the latest Org version). When I tried to run `M-x org-noter` inside a notes file I had, everything worked OK, so I could not reproduce your problem.

Are all your packages up to date? Could you also try using a plain Spacemacs without configuration (backup your .emacs.d and install it from scratch), and then following the steps above to see if it works?

**Comment by x61** [comment]
I tried but still can't get it to produce a pdf file.  This is what I did:
1. Create an org-file called `testNote.org`
2. Create a heading called `* This is a test`
3. Run `Mx- org-noter` but got a separate buffer with: 
`#+INTERLEAVE_PDF: ./* Sample
#+INTERLEAV_PDF: ~/Documents/testNote.pdf
`
There is no `pdf` file in the directory. Is this supposed to produce a pdf file? Did you have to install `pdf-tools`? I have it installed but with still with no success.

**Comment by x61** [comment]
Great, this works but I have a question.  In the Demo folder, I see three files
- Notes.org
- Demo.org and 
- Demo.pdf

However, we are editing Notes.org to update Demo.pdf? 
Why do we need Demo.org?
Does Demo.org get generated automatically?
I added a heading in Notes.org called Test then run `M-x org-noter` but it says `Invalid or document property found. Please specify document path`. What should I do here? link it to `Demo.pdf` or `Notes.org`?

**Comment by weirdNox** [comment]
Yeah, glad to hear that it works! 

> Notes.org to update Demo.pdf
> Does Demo.org get generated automatically

I think you have misunderstood the purpose of this package. The way org-noter works is by having the notes **separate** to the document itself. It does not generate new PDFs, neither it changes the original PDF to something else. You browse the notes in sync with the document by using the `org-noter` command. 

I wanted to have the notes separate in order to be able to quickly search through them, even with the PDF closed.

Also, don't mind Demo.org! It was the file used to generate the test PDF, it is not needed for the notes!

> link it to Demo.pdf or Notes.org?

You should link it to Demo.pdf, because the notes file is the one you are browsing currently.

> Lastly, do you define the PROPERTIES manually or are they defined automatically

PROPERTIES are defined automatically by using the commands available (like `org-noter-insert-note`, which is bound to `i` in the document buffer, inside a session). The list of keybindings is available in the README.

**Comment by bobberb** [comment]
Sorry if this is a hijack but regarding spacemacs:
Ctrl and M keys pressed together is RET in emacs - thus the key combination C-M-p/n/. are impossible to enter.

**Comment by weirdNox** [comment]
Hello @bobberb! C-M-p is Emacs slang for Control-Meta-p, which is the same, on many keyboard as Control-Alt-p. You may read more about that on the [Basic Keys](https://www.gnu.org/software/emacs/manual/html_node/efaq/Basic-keys.html) manual page and [here](https://www.gnu.org/software/emacs/manual/html_node/efaq/No-Meta-key.html#No-Meta-key).

**Comment by weirdNox** [comment]
No problem, ahah :)
