### ISSUE TITLE
Option for disabling window restore

### ISSUE THREAD

**Issue by oscarfv** [weirdNox/org-noter#2]
Hello. This is an interesting package, thanks for sharing!

When you navigate a document, maybe you want its window maximized for easy reading. But with org-noter, as soon as you reach a page with a note, the org-noter window reappears, shrinking the document's window. Sometimes you are not interested on the notes, or you have two monitors and can place the notes on another frame on another monitor.

What I propose is an option for restraining org-noter from automatically showing its window. The point on the org-noter buffer will change according to the current page on the document, but that's it. Advertising on the modeline that the current page has notes would be nice too.

**Comment by weirdNox** [comment]
I did it this way because, initially, this was a personal package, and most of the time I work with the two windows open. Also, at the moment, I don't support having the notes on a separate frame :/

What you propose is:
1. Inhibit notes from showing up
2. Show that there are some notes in the modeline
3. Separate frame for viewing notes

1 is easy and fast, will do it as soon as I can. I have never worked with the modeline, however 2 doesn't look hard to implement. 3 is a bit more involved for the reason I gave before, will probably take some time.

Thank you!

**Comment by oscarfv** [comment]
You're welcome.

The third point on your list is independent of the other two. I'm mainly interested on the first point, with the second as a related enhancement (you don't see the notes but you know that they exist). Once the first point is implemented, the user can arrange his UI as he pleases, because org-noter no longer will alter it.

**Comment by weirdNox** [comment]
Finally I got some time to work on this, I think this may be done on the latest commits, give it a try! 

It was a big refactor because of some dependencies I had on the notes window... So, if you find any bugs, please report them!

Also, check out the customization part of the readme, it has instructions for document level settings. If you want global settings, see you may want to change `org-noter-notes-window-behavior` and/or `org-noter-notes-window-location`.

**Comment by weirdNox** [comment]
Closing this for now. If any issue related to this comes up, feel free to reopen!
