### ISSUE TITLE
messed properties drawer

### ISSUE THREAD

**Issue by Jean-MichelC** [weirdNox/org-noter#20]
Hi again,

I have a systematic ID insertion in my org-headings.
This is achieved in my `init.el` by:
```elisp
(add-hook 'org-insert-heading-hook #'org-id-get-create)
```

This works fine, resulting, in org-mode (no `org-noter` call yet), after `S-RET` in:

```org
 * whatever heading title
      :PROPERTIES:
      :ID:       e14fff95-428b-4299-a325-3b08848ef777
      :END:
```

except that in `org-noter-doc-mode`, pressing `i` results in:

```org-mode
***** a note title
      :PROPERTIES:
      :NOTER_PAGE: 4
      :END:

      :PROPERTIES:
      :ID:       8c2dc0cb-dc06-40d9-a26f-78023d698422
      :END:
```
Instead of expected

```org
 ***** a note title
      :PROPERTIES:
      :NOTER_PAGE: 4
      :ID:       8c2dc0cb-dc06-40d9-a26f-78023d698422
      :END:
```
May-be ```org-noter``` inserts the property in an unusual way ?

**Comment by weirdNox** [comment]
Could you test this new version when it reaches MELPA? I couldn't reproduce it anymore with this fix :)

**Comment by Jean-MichelC** [comment]
OK : tested, and this is ok.
Thks !

Btw, I would love to understand your fix, but totally unable to. If you have 5 minutes, could you give me a hint ?

**Comment by weirdNox** [comment]
Great! 

Previously I was creating the heading, inserting the heading text, creating new lines after the heading so the cursor would be on the content and adding the property (which would be created above!).

The problem was that your hook added a property right when the heading was created, which means that the new lines would separate it from the heading, and it would stop being considered properties, so the last step would add the org noter properties above and your property would be below.

The fix was to make it create the heading, add the text, and then add the property. Then we go to the end of the element, but usually that it the start of the next one... So I go back until I find the `:` from `:END:` and add the newlines from there :)
