### ISSUE TITLE
Option for saving current page on exit

### ISSUE THREAD

**Issue by oscarfv** [weirdNox/org-noter#3]
PDF-tools has some limitations. One of the most glaring is the difficulty for keeping track of the last viewed page among sessions.

When you quit the session with org-noter, it would be very useful if the current page were saved as a property for the heading corresponding to the current document. Then, when visiting the document through org-noter, it could show that page.

Or maybe the current page stored in the notes file could be synchronized with the document. This frees the user from having to remember to quit the session before exiting Emacs, etc.

Since some users could prefer to not modify the file containing the notes, this feature would be controlled by an option.

**Comment by weirdNox** [comment]
Yes, this is a great idea! I can (and will!) implement this, but until the end of january I probably won't have time for it, because I'm studying for exams. If you want to give it a try and do it yourself before, send in a pull request.

However, maybe you don't know about it, but when opening a session, if the point is inside a specific note, it will open the document in the page of the note. While this is not the same as what you want, it may be a workaround while the option is not implemented!

For doing this manually, you may also use `org-noter-set-start-page`, which will do what you want, but you have to run this command before exiting, which is boring.

**Comment by weirdNox** [comment]
I think this is it! Please test it and see for yourself :)

**Comment by oscarfv** [comment]
Thank you. PDF-Tools is a bit limited as an ebook reader, but I hope that coupled with this package it will turn to be quite convenient for reading text books.

**Comment by weirdNox** [comment]
Yes, I've used this for a semester and I think having searchable notes with latex, kept in sync with the document is great for studying. 

Also, it finally solves my physical notes problem - I always ended up throwing everything away because it occupied space and I would never go back to them anyway, because searching my handwritten notes was slow.

Anyway, I hope this helps you, feel free to open more issues if you have more suggestions or bug reports!
