### ISSUE TITLE
Internal links are useless, and external links lack content

### ISSUE THREAD

**Issue by brabalan** [weirdNox/org-noter#33]
(Quick side note, org-noter is great. I've been spoiled by it and want more.)

When using hyperref, a lot of internal links are generated (to figures, lemmas, etc). Importing them as annotation is not very useful as it just states there is a link. Maybe internal links could be removed when importing links.

In addition, external links (to urls) do not have a contents associated with them. It would be useful to add it.

Thanks again for org-noter!

**Comment by weirdNox** [comment]
First of all, thanks for the kind words :) It's nice to know that something I created to help me study has been helpful to so many people!

About the internal links, maybe I could add a custom variable and then remove them when set. I'll see if I am able to distinguish them in order to do the filter.

In relation to the external links, you mean setting the heading as a Org link, right?

**Comment by weirdNox** [comment]
I think this does it, however I only tested with URIs, not remote documents. Check if it works for you! Don't hesitate to reopen any of the issues if the changes don't do their job :P

**Comment by brabalan** [comment]
It seems to be working, thanks!
