### ISSUE TITLE
Does Org-noter always open a new window ?

### ISSUE THREAD

**Issue by carlosgeos** [weirdNox/org-noter#42]
This is a question I have,

does it always open a new window ? I always end up with 2 instances of emacs.
Is there a way to keep the window where `M-x org-noter` is called ? I guess having isolated session is a feature, but is there any way to change it ?

(I am using `pdf-tools`)

Thanks !

**Comment by weirdNox** [comment]
Hello! You may configure it to use the current frame if there is no session on that frame, by changing `org-noter-always-create-frame`. 

You may also toggle it for that session only by doing `C-0 org-noter`, which you can use if you set the variable to t but you want it to open a specific session in a different frame anyway :)

**Comment by carlosgeos** [comment]
Alright, thanks !

**Comment by jingxuanlim** [comment]
Hi @carlosgeos and @weirdNox. I'm having trouble with this as well, despite setting `org-noter-always-create-frame` to `nil`. I think it has to do with the sessions, which is by default enabled on doomemacs? Not sure.

Any tips if the pdf is opened in a session? I wasn't able to do `C-0 org-noter` as `C-u 0 org-noter` was always called, which creates two new windows instead of an additional one.

Very much hoping to get some help as I've been pulling my hair out over this for the past few days. Thanks!
