### ISSUE TITLE
Annotate org documents

### ISSUE THREAD

**Issue by memeplex** [weirdNox/org-noter#46]
From a bit of trial & error this doesn't seem possible or, at least, simple. Am I missing something?

**Comment by weirdNox** [comment]
No, only `nov.el`, `pdf-tools` and `doc-view` are supported at the moment. 

There was a previous request about this but there was no conclusive way to annotate any kind of document. 

`org-noter` makes reference to specific places in the document (page number when using either `pdf-tools` or `doc-view`, or point information when using `nov.el`). The problem is that this relies on the annotated document being mostly static, or, at least, append only. As most PDFs, EPUBs or DJVUs don't change, there is no problem.

However, when using a generic file, there is no way to universally pinpoint a location, because it may change. We could use Org heading, but, even then, it may not be good enough to associate unambiguously (a lot of text inside the same heading, for example), and it only applies to Org files.

Besides, when calling `org-noter` in an Org file, it currently asks you for a document to annotate. If not in an Org file, it searches for one that is annotating the current document or creates the heading in the best match (or asks you for a target Org file).

If Org files start being annotated, there would be no way to distinguish both use cases. It may not be a problem for most of the time, but it could be confusing.

**Comment by memeplex** [comment]
Ok, I'm closing this, it's good enough to use COMMENT annotated sections inside the document, I was just asking, thanks for the detailed explanation!

**Comment by weirdNox** [comment]
No problem! Now, when someone else asks about this feature or similar, I can point them to this and someone may even think of solutions to these problems :)

Thanks!
