### ISSUE TITLE
File format support

### ISSUE THREAD

**Issue by baudtack** [weirdNox/org-noter#55]
It's unclear to me what file formats are supported. I'm trying to use it with a txt file but it doesn't seem to work giving me 

```org-noter--create-session: This document handler is not supported :/```

Is this just because txt is not support or am i doing something wrong? I have also tried it with markdown files and get the same result. is this intended only for use with pdf/ps kinds of files?

**Comment by weirdNox** [comment]
Yes, this is intended to annotate mostly paginated formats like PDFs and DJVUs. However, it also supports everything that is supported by doc-view (Emacs built-in), so you can annotate Words and the like (how well it works depends on how well it is supported by doc-view), and EPUBs through nov.el.

Simple text files, not being paginated and usually being highly "volatile" (changed regularly), would not be a good annotation target, because there are no reference points per say. With EPUBs, I got away by targeting text positions because they are mostly static.

**Comment by baudtack** [comment]
Fair enough. Sadly outside of my use case. Still a pretty sick project.

**Comment by weirdNox** [comment]
Thanks! I hope you find something that fits your needs :)

**Comment by xuning97** [comment]
is it possible to support code file format, like .cpp, .java, .go, It would be very useful for code reading and annotation.
