### ISSUE TITLE
Cannot use a question mark in the note title prompt

### ISSUE THREAD

**Issue by rosetree** [weirdNox/org-noter#60]
Thank you, for this document management and note taking package! It’s great and I like it.

Sometimes I want to add notes that have a question as a title, like “What are the scheduling algorithms of an interactive operating system?”. However, if I try to end the question with “?”, the question mark is not printed. Instead the following message appears: `[No completions]` My current workaround is to leave the question mark away and add it later in the Notes window.

I guess that this happens with [`completion-read` in line 1652](https://github.com/weirdNox/org-noter/blob/d8e88185ae755141c09d296d272e49736b18421b/org-noter.el#L1652). This could probably be resolved when using `read-string` or `read-from-minibuffer` instead (as described in [Text from Minibuffer](https://www.gnu.org/software/emacs/manual/html_node/elisp/Text-from-Minibuffer.html)). But I’m not sure: is this completion is used for a reason or could it be replaced without breaking another feature?

**Comment by weirdNox** [comment]
Hi there! Thanks for the heads up!
`completing-read` is used because it will show the existing notes that are active on the current page, so you can select one of those if you want to add more information.
There is no problem using `ivy`, so it is implementation defined. It looks like `minibuffer-completion-help` is bound to `?` using the default `completing-read`.
I believe that you are able to insert a question mark if you press `C-q` before pressing `?`, as that command inserts the character you write without interpreting it. You could also remove the binding of `?` from `minibuffer-local-completion-map`, if you don't use that feature.
Another way would be to advise the `org-noter` insert function in order to make `completing-read` an alias to `read-string`.

**Comment by rosetree** [comment]
Thank you for your answer and pointing out the reason behind using `completing-read`. From the alternatives, I choose to remove `?` from the map and give that configuration a try. Using `C-q ?` works as well, but as tab-completion doesn’t the `?` binding, I try to save that keystrokes. Thanks for your fast help.

(In my case this looks like `(use-package org-noter :config (define-key minibuffer-local-completion-map (kbd "?") nil))` if anyone is interested.)
