### ISSUE TITLE
Support single frame based workflows

### ISSUE THREAD

**Issue by dzop** [weirdNox/org-noter#63]
I prefer to use a single frame along with the [perspective](https://github.com/nex3/perspective-el) package to manage my window configurations instead of having multiple frames open. Would it be possible to support this use case instead of falling back to opening a new frame for every session other than the first?

Possibly the simplest solution would be to abstract out the frame creation code into a customizable function that I can then set for my own purposes? I haven't looked through the code very much so I'm not sure how important it is to have a frame associated with a session, but I would think a session only needs to link the PDF buffer and the `org-mode` buffer.

I'd be happy to work with you to come up with a solution if you let me know the role that the frame plays in a session.

Great job on the package by the way.

**Comment by weirdNox** [comment]
Hi there! Thanks for the suggestion :)

Is the variable `org-noter-always-create-frame` sufficient for your needs? If `nil`, it only creates a frame when no other session is open on the current frame (it is not possible to have multiple sessions per frame).

**Comment by dzop** [comment]
Yes, the variable works great for having one session on the current frame, but why is it not possible to have multiple sessions per frame? I would think that a session is just a link between an `org-mode` buffer and a `pdf` buffer.

My workflow can be thought of as more of a tab-based workflow and I would like to have multiple sessions opened for the various "tabs" I have containing my notes. I could easily just quit the current session when switching to a different tab and then start a new session in the new tab, but I don't see why this would be necessary if I consider a session to be an association between a `pdf` and an `org-mode` buffer. What role does the frame play in how `org-noter` works that makes it important for a session?

**Comment by weirdNox** [comment]
I have used modes that had no window management on their part (only buffer creation) or only at the beginning to setup all the windows, and then it would be somewhat confusing due to not having a separation between different sessions, and for some, when I terminated them, the buffers would lie around and I'd have to either reorganize the windows the way I wanted or I'd just create a new frame and delete the previous one and be done with it.

But I understand your reasoning, and I think that it is possible. This was an arbitrary decision on my part.

However, I don't have much time to look into it, because we would have to change all window management logic to have two different modes (for example, currently it sets the PDF as dedicated, meaning it cannot be changed, which probably doesn't make much sense if what you proposed was the way this worked) and to change everything that handles frames to don't create them and rename them.

If you look into it, it may not be that much work, but there may be some edge cases where it works for the current behaviour only, I don't know.

Some things that probably need to be changed, off the top of my head:
- Dedicated doc window
- Notes buffer creation/search (maybe it would just work?)
- Removal of the checks of an existing session (conditionally, if you want it to be a setting)
- Frame creation
- Frame check in session validation

**Comment by dzop** [comment]
Thanks for the response. I have had some success with removing various parts of the frame creation and deletion stuff which allows me to create multiple sessions in a single frame. I will try to work out a pull request after investigating more thoroughly.

I guess the best way to go about adding the new behavior would be to introduce a third option to `org-noter-always-create-frame`, something like `never` to cause `org-noter` to only use the selected frame?

**Comment by weirdNox** [comment]
Hello, and sorry for the delay, I have been very busy these last weeks...
I appreciate the pull request, if you are willing to do it! Thanks! 

The `never` option would be great. After that we could also create a special command that overrides the option to do that :)

**Comment by nnicandro** [comment]
I spoke too soon. I switched over to a different OS ([GuixSD](https://guix.gnu.org/)) and am using [Sway](https://swaywm.org/), a window manager. With this setup I no longer use just a single Emacs frame and your way of doing things works out perfectly.

Closing this issue now.

**Comment by weirdNox** [comment]
Great, I'm happy that this workflow now fits your needs, and that it works fine with i3/sway; I've been thinking about trying them out, when I have free time.

Unfortunately I have had no time at all, so the issues for this package also take a long time to be resolved, especially if they are relative to new features. I use it almost every day, but I don't encounter any bugs anymore, and I'm really happy with it, so I don't feel compelled to implement new stuff!
