### ISSUE TITLE
work with org-attach

### ISSUE THREAD

**Issue by shelper** [weirdNox/org-noter#66]
now if i run org-noter on a headline, it ask for the path for the pdf file 
but org mode actually come with org-attach, which would be useful if org-noter automatically find the attached file and i dont have to type any more 
is this an easy feature to add?

**Comment by weirdNox** [comment]
This has been on my backlog for quite some time, thanks for reminding me!

**Comment by rosetree** [comment]
This would probably also enhance the combination with [org-brain](https://github.com/Kungsgeten/org-brain/), which supports attachments from the visualized setting.

What would you do about multiple attachments? Should the first selection add a document property or should the attachment always be selected again? Both seem to be useful. The second approach is not as fast for future noter sessions, but allows to share notes between different versions of a document.

**Comment by weirdNox** [comment]
I was thinking of asking which file we wanted to use as document, on the first run, and saving that as `NOTER_DOCUMENT`; then it would work as it works now.

I wasn't planning on supporting multiple documents because, even with versions of the same document, it could change significantly, having the same content on different pages, which would make `org-noter` useless (at least with my type of annotations, see [fuxialexander/org-pdftools](https://github.com/fuxialexander/org-pdftools)).

However, I could also implement a function that lists once again the different attachments, and changes `NOTER_DOCUMENT` accordingly before calling `org-noter`, which you could use to override the version you're seeing.

**Comment by weirdNox** [comment]
I believe this is done! Please test it and report back :)

Also, if you want to choose another attached file, use 2 universal prefix arguments when executing `org-noter`, which overrides the annotated document. You could write a wrapper for that, if you use it a lot.

**Comment by yiufung** [comment]
Just to say this is really really useful feature and thanks for working on it! Discovering `org-attach` and `org-noter` individually have given me so much help, and combining them is just magnificence at another level. This could've been in README for more attention. Thanks again for the great work!

**Comment by weirdNox** [comment]
I always forget to add new features to the README! :D
Thanks for the kind words and for the reminder :)
