### ISSUE TITLE
Interleave without org-mode

### ISSUE THREAD

**Issue by rien333** [weirdNox/org-noter#70]
Given the name of project this might be a completely irrelevant issue  (I might try and open this issue in the somewhat   abandoned [interleave-mode](https://github.com/rudolfochrist/interleave) repo), but would it be doable to use the functionality of this project without org? In essence, this would mean interleaving a pdf with  a non-org mode buffer (say markdown or something even more basic). I'm a pretty hardcore markdown user, and I'm under the impression that md has at least a few of the capabilities of org-mode,  at least in regard to note-taking.

I know, a loyal emacs users that doesn't know/use org, strange huh? I suppose I would enjoy or benefit from org (after at least some time), but I don't really feel like learning and using yet another big thing, and certainly not only to be able to take notes on a pdf. (I haven't really found anything in org that has convinced me to learn it or devote a large chunk of my time to mastering it). It would be nice to have support for non-org modes given that there are probably others looking for something "simpler" or that are less sucked into the emacs ecosystem.

**Comment by weirdNox** [comment]
I understand why you would want something like that, and it would be doable as a project if the the format you want (ie. Markdown) supports having metadata in the text. 

However, as you assume correctly, this heavily depends on Org-mode; if you open the source you'll see calls to Org functions everywhere around the code, as this uses it as a backbone - for example, instead of searching for the properties using regex, this uses Org's functions to iterate over the code.

As such, changing this to include Markdown compatibility would be like rewriting the entire package, as one would have to change almost every single function.
I'm not really interested in having a Markdown version of this, as I don't use Markdown myself nor have the time to invest.

About interleave-mode, I believe Sebastian abandoned it because he stopped using this kind of stuff completely (I spoke with him when I created this alternative package).

**Comment by rien333** [comment]
I see, thank you for your insights!
